version: '3.8'

services:
  detector:
    image: cyberwitness-detector
    build: .
    environment:
      - BPF_FILTER=tcp port 80 or 443
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '2'
          memory: 4G

  elasticsearch:
    image: elasticsearch:8.5.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: kibana:8.5.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch