version: '3.8'

services:
  cyberwitness:
    build: .
    container_name: cyberwitness
    environment:
      - BPF_FILTER=tcp port 80 or 443
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/var/log/cyberwitness
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G

  elasticsearch:
    image: elasticsearch:8.5.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: kibana:8.5.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch